### Imports

In [6]:
%pylab inline 
import os
import nibabel as nib
import numpy as np
from glob import glob
from scipy.ndimage import label

Populating the interactive namespace from numpy and matplotlib


##### Load the text file with mse ids

In [4]:
subjects = np.genfromtxt("pbr_baselines.txt", dtype=str)
print subjects[:5]

['mse1328' 'mse1334' 'mse1337' 'mse1343' 'mse1349']


##### define some paths to data

In [ ]:
base_dir = "/data/henry7/PBR/subjects/"
template = "{base_dir}/{mseid}/lesions_manual/*/alignment_lesions.nii.gz"

## figure out a way to fill the template and glob for the file you need

In [ ]:
lesion_file = #fill the template with the first subject, subjects[0]

## Load an image

In [ ]:
img = nib.load(lesion_file)
data, affine = nib.get_data(), nib.get_affine()

## Number each lesion 

In [ ]:
labels, nlabels = label(data==1)

## Get x,y,z coordinates for each lesion

In [ ]:
np.nonzero

## Tranform coordinates to world space

In [1]:
np.dot([x,y,z,1], aff) #order might be switched 

NameError: name 'np' is not defined

In [2]:
subjects = np.genfromtxt("pbr_baselines.txt", dtype=str)
print subjects[:5]

NameError: name 'np' is not defined

In [1]:
%pylab inline 
import os
import nibabel as nib
import numpy as np
from glob import glob
from scipy.ndimage import label

Populating the interactive namespace from numpy and matplotlib


In [2]:
subjects = np.genfromtxt("pbr_baselines.txt", dtype=str)
print subjects[:5]

['mse1328' 'mse1334' 'mse1337' 'mse1343' 'mse1349']


In [3]:
import glob
import nibabel as nib

In [4]:
ms1328 = "/data/henry7/PBR/subjects/mse1328/lesions_manual/ms56-mse1328-002-AX_T1_3D_IRSPGR/alignment_lesions.nii.gz"

In [5]:
for lesion_file_1328 in glob.glob("/data/henry7/PBR/subjects/mse1328/lesions_manual/*/alignment_lesions.nii.gz"):
    print lesion_file_1328

/data/henry7/PBR/subjects/mse1328/lesions_manual/ms56-mse1328-002-AX_T1_3D_IRSPGR/alignment_lesions.nii.gz


In [6]:
img1328 = nib.load(lesion_file_1328)
img1328.dataobj

In [7]:
data1328 = img1328.get_data()
data1328.shape


(256, 256, 150)

In [8]:
affine1328 = img1328.get_affine()
print affine1328

[[  -0.9375        0.            0.          123.6289978 ]
 [   0.            0.9375        0.          -93.36050415]
 [   0.            0.            1.          -44.42710114]
 [   0.            0.            0.            1.        ]]


In [9]:
labels, nlabels = label(data1328==[1])

In [10]:
nlabels

11

In [11]:
n = np.unique(labels)
print n

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [12]:
np.bincount(labels.ravel())

array([9829648,      69,     105,      54,      29,      69,      61,
            36,      47,     125,     111,      46])

In [13]:
def coordinates(n):
    for value in n: 
        if value == n and n != 0:
            x,y,z = np.nonzero(labels)
            print "x", x
            print "y", y
            print "z", z
        else:
            print none

In [49]:
def get_lesion_coord():
    all_lesion = []
    for count in range(1, nlabels+1):
        cur_lesion = []
        x,y,z = np.nonzero(labels==count)
        for count2 in range(len(x)):
            cur_coordinates = [x[count2],y[count2],z[count2]]
            cur_lesion.append(cur_coordinates)
        all_lesion.append(cur_lesion)
    for count in range(nlabels):
        print "lesion #", count+1, "", all_lesion[count]
        print ""
    return all_lesion

get_lesion_coord()


lesion # 1  [[76, 105, 89], [76, 105, 90], [76, 106, 89], [76, 106, 90], [76, 106, 91], [76, 107, 89], [76, 107, 90], [76, 107, 92], [77, 104, 89], [77, 105, 88], [77, 105, 89], [77, 105, 90], [77, 105, 91], [77, 106, 88], [77, 106, 89], [77, 106, 90], [77, 106, 91], [77, 106, 92], [77, 107, 88], [77, 107, 89], [77, 107, 90], [77, 107, 91], [77, 107, 92], [77, 108, 89], [77, 108, 90], [78, 104, 88], [78, 104, 89], [78, 105, 88], [78, 105, 89], [78, 105, 90], [78, 105, 91], [78, 106, 88], [78, 106, 89], [78, 106, 90], [78, 106, 91], [78, 107, 88], [78, 107, 89], [78, 107, 90], [78, 108, 89], [79, 104, 88], [79, 104, 89], [79, 105, 88], [79, 105, 89], [79, 105, 90], [79, 106, 88], [79, 106, 89], [79, 106, 90], [79, 107, 88], [79, 107, 89], [79, 107, 90], [79, 108, 89], [80, 104, 88], [80, 104, 89], [80, 105, 88], [80, 105, 89], [80, 105, 90], [80, 106, 88], [80, 106, 89], [80, 106, 90], [80, 107, 88], [80, 107, 89], [80, 108, 88], [81, 105, 88], [81, 105, 89], [81, 106, 88], [81, 106, 89

[[[76, 105, 89],
  [76, 105, 90],
  [76, 106, 89],
  [76, 106, 90],
  [76, 106, 91],
  [76, 107, 89],
  [76, 107, 90],
  [76, 107, 92],
  [77, 104, 89],
  [77, 105, 88],
  [77, 105, 89],
  [77, 105, 90],
  [77, 105, 91],
  [77, 106, 88],
  [77, 106, 89],
  [77, 106, 90],
  [77, 106, 91],
  [77, 106, 92],
  [77, 107, 88],
  [77, 107, 89],
  [77, 107, 90],
  [77, 107, 91],
  [77, 107, 92],
  [77, 108, 89],
  [77, 108, 90],
  [78, 104, 88],
  [78, 104, 89],
  [78, 105, 88],
  [78, 105, 89],
  [78, 105, 90],
  [78, 105, 91],
  [78, 106, 88],
  [78, 106, 89],
  [78, 106, 90],
  [78, 106, 91],
  [78, 107, 88],
  [78, 107, 89],
  [78, 107, 90],
  [78, 108, 89],
  [79, 104, 88],
  [79, 104, 89],
  [79, 105, 88],
  [79, 105, 89],
  [79, 105, 90],
  [79, 106, 88],
  [79, 106, 89],
  [79, 106, 90],
  [79, 107, 88],
  [79, 107, 89],
  [79, 107, 90],
  [79, 108, 89],
  [80, 104, 88],
  [80, 104, 89],
  [80, 105, 88],
  [80, 105, 89],
  [80, 105, 90],
  [80, 106, 88],
  [80, 106, 89],
  [80, 106, 90

In [46]:
def average_les(coordinates):
    averages_all = []
    for count in range(len(coordinates)):
        averages = []
        sumx=0;sumy=0;sumz=0
        for count2 in range(len(coordinates[count])):
            sumx += coordinates[count][count2][0]
            sumy += coordinates[count][count2][1]
            sumz += coordinates[count][count2][2]
        average_x = sumx / len(coordinates[count])
        average_y = sumy / len(coordinates[count])
        average_z = sumz / len(coordinates[count])
        averages = [average_x, average_y, average_z]
        averages_all.append(averages)
        print count, averages
    return averages_all

print average_les(all_lesion)


0 [78, 105, 89]
1 [86, 126, 82]
2 [91, 93, 58]
3 [90, 98, 50]
4 [99, 82, 55]
5 [102, 74, 61]
6 [113, 77, 82]
7 [146, 102, 89]
8 [148, 148, 89]
9 [150, 115, 101]
10 [151, 106, 92]
[[78, 105, 89], [86, 126, 82], [91, 93, 58], [90, 98, 50], [99, 82, 55], [102, 74, 61], [113, 77, 82], [146, 102, 89], [148, 148, 89], [150, 115, 101], [151, 106, 92]]


In [ ]:
x,y,z = np.nonzero(labels== )
print "x", x
print "y", y
print "z", z

In [ ]:
np.dot(average(x,y,z),1, affine1328)

In [47]:
x,y,z = np.nonzero(labels==2)
print "x", x
print "y", y
print "z", z

x [83 83 83 83 83 83 83 83 83 83 84 84 84 84 84 84 84 84 84 84 84 84 84 84 84
 84 85 85 85 85 85 85 85 85 85 85 85 85 85 85 85 85 85 86 86 86 86 86 86 86
 86 86 86 86 86 86 86 86 86 86 87 87 87 87 87 87 87 87 87 87 87 87 87 87 87
 87 87 87 87 88 88 88 88 88 88 88 88 88 88 88 88 88 88 88 88 89 89 89 89 89
 89 89 89 90 90]
y [126 126 126 126 127 127 127 127 128 128 125 125 125 126 126 126 126 126
 127 127 127 127 127 128 128 128 124 125 125 125 125 126 126 126 126 126
 127 127 127 127 127 128 128 124 125 125 125 125 126 126 126 126 126 127
 127 127 127 127 128 128 124 124 125 125 125 125 126 126 126 126 126 127
 127 127 127 127 128 128 128 124 125 125 125 125 126 126 126 126 126 127
 127 127 127 127 128 125 125 126 126 126 126 127 128 126 127]
z [80 81 83 84 80 81 83 84 81 83 81 83 84 80 81 82 83 84 80 81 82 83 84 80 81
 83 83 81 82 83 84 80 81 82 83 84 80 81 82 83 84 81 83 83 81 82 83 84 80 81
 82 83 84 80 81 82 83 84 81 83 83 84 81 82 83 84 80 81 82 83 84 80 81 82 83
 84 80 81 83 83 81

In [48]:
def average(x,y,z):
    sumx = 0; sumy = 0; sumz = 0
    count = 0
    for count in range(len(x)):
        sumx += x[count]
        sumy += y[count]
        sumz += z[count]
    average_x = sumx / len(x)
    average_y = sumy / len(y)
    average_z = sumz / len(z)
    averages = [average_x, average_y, average_z]
    return averages

print average(x,y,z)

[86, 126, 82]
